"""TranscriptProviderPort backed by youtube-transcript-api.

YouTube exposes several kinds of caption tracks that are NOT equivalent:

  * **manual**      — written/uploaded by the author at publication time (human quality)
  * **generated**   — auto-generated by YouTube's speech recognition (ASR, lower quality)
  * **translated**  — machine-translated from another track (variable quality)

Rather than blindly taking the first track YouTube returns, this adapter *lists*
the available tracks and picks the most trustworthy one, in this order:

  1. manual track in a preferred language
  2. manual track in any language
  3. ASR track in a preferred language        (skipped if accept_asr=False)
  4. ASR track in any language                (skipped if accept_asr=False)
  5. translate any track into a preferred language (only if enable_translation=True)

Returns None when nothing acceptable is found (transcripts disabled, none exist,
only ASR while ASR is refused, or a network error). The use case then marks the
video as unavailable.

Supports both the 1.x instance API (`list`/`fetch`) and the legacy 0.6.x static API.
"""

from __future__ import annotations

import structlog
from youtube_transcript_api import YouTubeTranscriptApi

from ..domain.models import Transcript, TranscriptSegment, TranscriptSource

log = structlog.get_logger(__name__)


class YouTubeTranscriptProvider:
    def __init__(self, *, accept_asr: bool = True, enable_translation: bool = False) -> None:
        # Accept YouTube's auto-generated captions. Turn off to mark ASR-only
        # videos as unavailable instead of using YouTube ASR.
        self._accept_asr = accept_asr
        # Machine-translate an existing track as a last resort.
        self._enable_translation = enable_translation

    def fetch(self, video_id: str, languages: list[str]) -> Transcript | None:
        try:
            selected = self._select(video_id, languages)
        except Exception as exc:  # noqa: BLE001 - any failure means "no transcript"
            log.info("transcript.unavailable", video_id=video_id, error=str(exc))
            return None

        if selected is None:
            return None
        raw, language, source = selected

        segments = [
            TranscriptSegment(
                start_s=float(item["start"]),
                duration_s=float(item.get("duration", 0.0)),
                text=item["text"],
            )
            for item in raw
        ]
        if not segments:
            return None
        log.info(
            "transcript.selected",
            video_id=video_id,
            source=source.value,
            language=language,
            segments=len(segments),
        )
        return Transcript(language=language, source=source, segments=segments)

    # -- selection strategy --------------------------------------------------

    def _select(
        self, video_id: str, languages: list[str]
    ) -> tuple[list[dict], str, TranscriptSource] | None:
        """Pick the most trustworthy acceptable track, or None."""
        api = YouTubeTranscriptApi()

        # Legacy 0.6.x has no `list`; fall back to the old flat behaviour.
        if not hasattr(api, "list"):
            raw = YouTubeTranscriptApi.get_transcript(  # type: ignore[attr-defined]
                video_id, languages=languages
            )
            lang = languages[0] if languages else "unknown"
            # We can't tell manual from ASR on the legacy API — assume ASR (worst case).
            return raw, lang, TranscriptSource.YOUTUBE_ASR

        transcript_list = api.list(video_id)
        manual = [t for t in transcript_list if not t.is_generated]
        generated = [t for t in transcript_list if t.is_generated]

        # 1-2. author-written captions win, preferred language first.
        chosen = self._first_in_languages(manual, languages) or (manual[0] if manual else None)
        if chosen is not None:
            return self._fetch(chosen, TranscriptSource.YOUTUBE_MANUAL)

        # 3-4. YouTube ASR, if we accept it.
        if self._accept_asr:
            chosen = self._first_in_languages(generated, languages) or (
                generated[0] if generated else None
            )
            if chosen is not None:
                return self._fetch(chosen, TranscriptSource.YOUTUBE_ASR)

        # 5. last resort: machine-translate any translatable track.
        if self._enable_translation and languages:
            for track in list(transcript_list):
                if getattr(track, "is_translatable", False):
                    translated = track.translate(languages[0])
                    return self._fetch(translated, TranscriptSource.YOUTUBE_TRANSLATED)

        return None

    @staticmethod
    def _first_in_languages(tracks: list, languages: list[str]):
        """First track whose language matches a preference, honouring order."""
        for lang in languages:
            for track in tracks:
                if track.language_code == lang or track.language_code.startswith(f"{lang}-"):
                    return track
        return None

    @staticmethod
    def _fetch(track, source: TranscriptSource) -> tuple[list[dict], str, TranscriptSource]:
        fetched = track.fetch()
        raw = [{"text": s.text, "start": s.start, "duration": s.duration} for s in fetched]
        return raw, track.language_code, source
