"""Pure domain entities. No framework / IO dependencies here (Clean Architecture)."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path


class TranscriptSource(str, Enum):
    """Where a transcript came from, ordered from most to least trustworthy.

    YouTube exposes several kinds of caption tracks that must NOT be treated
    alike: a track written by the author is human-quality, whereas an ASR track
    is machine-guessed and a translated track is machine-translated on top.
    """

    YOUTUBE_MANUAL = "youtube_manual"  # captions written/uploaded by the author (human)
    YOUTUBE_ASR = "youtube_asr"  # auto-generated by YouTube speech recognition
    YOUTUBE_TRANSLATED = "youtube_translated"  # machine-translated from another track

    @property
    def is_youtube(self) -> bool:
        return self in {
            TranscriptSource.YOUTUBE_MANUAL,
            TranscriptSource.YOUTUBE_ASR,
            TranscriptSource.YOUTUBE_TRANSLATED,
        }

    @property
    def is_human(self) -> bool:
        """True only for author-written captions (highest confidence)."""
        return self is TranscriptSource.YOUTUBE_MANUAL


class TranscriptStatus(str, Enum):
    AVAILABLE = "available"
    UNAVAILABLE = "unavailable"  # no YouTube captions available


@dataclass(frozen=True, slots=True)
class VideoMetadata:
    video_id: str
    url: str
    title: str
    channel: str | None = None
    duration_s: int | None = None
    upload_date: str | None = None
    language: str | None = None


@dataclass(frozen=True, slots=True)
class AudioAsset:
    path: Path
    format: str
    sample_rate: int | None = None


@dataclass(frozen=True, slots=True)
class TranscriptSegment:
    start_s: float
    duration_s: float
    text: str


@dataclass(frozen=True, slots=True)
class Transcript:
    language: str
    source: TranscriptSource
    segments: list[TranscriptSegment]

    @property
    def text(self) -> str:
        return " ".join(seg.text.strip() for seg in self.segments if seg.text.strip())


@dataclass(frozen=True, slots=True)
class IngestionResult:
    metadata: VideoMetadata
    audio: AudioAsset
    transcript: Transcript | None
    transcript_status: TranscriptStatus
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    # filled in after persistence
    language: str | None = None
    storage_uri: str | None = None


class JobStatus(str, Enum):
    PENDING = "pending"  # accepted by the API, queued on Kafka
    RUNNING = "running"  # picked up by a worker
    COMPLETED = "completed"
    FAILED = "failed"  # sent to the DLQ


@dataclass(frozen=True, slots=True)
class Job:
    job_id: str
    url: str
    languages: list[str]
    status: JobStatus = JobStatus.PENDING
    result_uri: str | None = None
    error: str | None = None
    # YouTube video id derived from `url` at creation, used to de-duplicate jobs.
    video_id: str | None = None
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
