"""Pure domain entities. No framework / IO dependencies here (Clean Architecture)."""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from pathlib import Path


class TranscriptSource(str, Enum):
    """Where a transcript came from."""

    YOUTUBE = "youtube"  # captions provided by YouTube
    STT = "stt"  # generated by a speech-to-text model (Phase 2)


class TranscriptStatus(str, Enum):
    AVAILABLE = "available"
    UNAVAILABLE = "unavailable"  # no YouTube captions and no STT wired


@dataclass(frozen=True, slots=True)
class VideoMetadata:
    video_id: str
    url: str
    title: str
    channel: str | None = None
    duration_s: int | None = None
    upload_date: str | None = None
    language: str | None = None


@dataclass(frozen=True, slots=True)
class AudioAsset:
    path: Path
    format: str
    sample_rate: int | None = None


@dataclass(frozen=True, slots=True)
class TranscriptSegment:
    start_s: float
    duration_s: float
    text: str


@dataclass(frozen=True, slots=True)
class Transcript:
    language: str
    source: TranscriptSource
    segments: list[TranscriptSegment]

    @property
    def text(self) -> str:
        return " ".join(seg.text.strip() for seg in self.segments if seg.text.strip())


@dataclass(frozen=True, slots=True)
class IngestionResult:
    metadata: VideoMetadata
    audio: AudioAsset
    transcript: Transcript | None
    transcript_status: TranscriptStatus
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
